### ISSUE TITLE
EFLOW connection to VM throwing certificate errors

### ISSUE THREAD

**Issue by maggiojoe2** [Azure/iotedge-eflow#305]
**Describe the bug**
Unable to connect to eflow vm because of authentication certificate error.

I have two devices with this issues so far, but haven't tested enough to know how widespread it is.

These devices have been running for over a year without issues. The IoT deployment is still on them and they are running, IoT Hub can communicate with them. I just can't get into the VM to debug issues.

**To Reproduce**
`PS C:\WINDOWS\system32> Connect-EflowVm

[07/17/2025 10:00:10] Exception caught!!!

 - C:\Program Files\Azure IoT Edge\nodectl.exe  compute vm list -o tsv --query "[*].name" failed to execute [Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2025-07-17T10:00:10-05:00 is after 2025-07-15T19:17:31Z"] at line 4349

[07/17/2025 10:00:10] Exception caught!!!

 - Failed to retrieve virtual machine name. at line 3060`

This was the first error I saw when running Connect-EflowVm. After some research I found the suggestion from this release to run updateWssdCert.ps1

https://github.com/Azure/iotedge-eflow/releases/tag/1.4.3.23013

This resulted in the following errors:

`Remove-Item : Cannot find path 'C:\Users\cyclops\.wssd\nodectl' because it does not exist.
At C:\Users\cyclops\Downloads\updateWssdCert.ps1:17 char:1
+ Remove-Item -Recurse -Force -Path "$env:UserProfile\.wssd\nodectl"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\cyclops\.wssd\nodectl:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Copy-Item : A positional parameter cannot be found that accepts argument 'Â'.
At C:\Users\cyclops\Downloads\updateWssdCert.ps1:21 char:1
+ Copy-Item -Path "$env:UserProfile\.wssd\nodectl\cloudconfig"Â  -Desti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

[07/17/2025 10:10:05] Exception caught!!!

 - C:\Program Files\Azure IoT Edge\nodectl.exe  compute vm list -o tsv --query "[*].name" failed to execute [Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"NodeAgent\")"] at line 4349
Error caught while invoking VM command
Failed to retrieve virtual machine name.`

Now when I run the connect command again I am getting this error:
`- C:\Program Files\Azure IoT Edge\nodectl.exe  compute vm list -o tsv --query "[*].name" failed to execute [Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"NodeAgent\")"] at line 4349`

**Expected behavior**
Connect-EflowVm should not have certificate errors.

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 Professional
 - Version: 22H2
 - Virtual Machine: Local VM

**Comment by josephknierman** [comment]
@maggiojoe2 the issue you were seeing there should be fixed by the PR here https://github.com/Azure/iotedge-eflow/pull/306. if you run the script from https://github.com/Azure/iotedge-eflow/blob/main/eflow-util/updateWssdCert.ps1 it should work now.

**Comment by maggiojoe2** [comment]
The issue is not caused by what that PR fixed, but the fix can now be applied by that script.

I found another device with the original issue today. Script fixed it, but still threw an error.

```

Remove-Item : Cannot find path 'C:\Users\cyclops\.wssd\nodectl' because it does not exist.
At line:17 char:1
+ Remove-Item -Recurse -Force -Path "$env:UserProfile\.wssd\nodectl"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\cyclops\.wssd\nodectl:String) [Remove-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand


```

So the script is still throwing errors.

Also, the ORIGINAL problem seems to still be around. Why am I seeing this error randomly on some of my devices?

```PS C:\WINDOWS\system32> Connect-EflowVm

[07/17/2025 10:00:10] Exception caught!!!

    C:\Program Files\Azure IoT Edge\nodectl.exe compute vm list -o tsv --query "[*].name" failed to execute [Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2025-07-17T10:00:10-05:00 is after 2025-07-15T19:17:31Z"] at line 4349

[07/17/2025 10:00:10] Exception caught!!!

    Failed to retrieve virtual machine name. at line 3060```

**Comment by josephknierman** [comment]
@maggiojoe2 just to check the directory "C:\Users\cyclops\.wssd\nodectl" does not exist on your system right? perhaps this script ran partially before but then failed.

could you try the following.
1. Verify that the directory "C:\Users\cyclops\.wssd\nodectl" is not on your system, but the directory C:\Users\cyclops\.wssd exists. If this is not the case let me know.
2. modify the script https://github.com/Azure/iotedge-eflow/blob/main/eflow-util/updateWssdCert.ps1, and remove the line "Remove-Item -Recurse -Force -Path "$env:UserProfile\.wssd\nodectl"
3. run the modified updateWssdCert.ps1 in an admin powershell isnatnce.

**Comment by SummerSmith** [comment]
@maggiojoe2, were you able to run the steps Joseph suggested above?

**Comment by SummerSmith** [comment]
I will close this issue, as we haven't heard back in a while. Please reopen this or create a new issue if this persists on the latest version.
